apiVersion: v1
kind: Service
metadata:
  name: devops-k8s-app-service
  labels:
    app: devops-k8s-app
spec:
  type: LoadBalancer
  selector:
    app: devops-k8s-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: None
